package main

import (
	"log"
	"time"

	"github.com/Petrosz007/hasznaltauto-watcher/internal/crawler"
	"github.com/Petrosz007/hasznaltauto-watcher/internal/db"
)

func main() {
	dbPath := "db.sql"
	err := db.Migrate(dbPath)
	if err != nil {
		log.Fatal(err)
	}

	testSearchQueryUrl := "https://www.hasznaltauto.hu/talalatilista/PCOG2VG3R3RDADH5S56ADFGLZSCMOXNBIVNKDEKWTLL4UUCTIKJRQJLJGWAPR53V3LBDIFKPWWHOH6HY7CSCAZY76LTOKNETUKBIAJJZAVNWZREKWGURJ7UKA32QL2SAFU2JOATUPJYNXY2H4UFAZ2A3FDAF7RLKE4T72JINYMNFY3UURWLUZJAQ4MGHYDZTBMU3A5TZKK3X3FMIMXH75XGVQIHPSCM4VHNXXJEYW3PTOKKKOBQPOCVU6IXQ4ZDRKLIGIX7EXDTQ4HPKEMDHVEP6SCBPTEKXAFB4QH3NY2ZNAGSOAFHA7HAHHXYAILGUU2QB5GZ6WHA4AQ7QGEWE7Y6Q245PQSDAYZCCNE4WZL5XQCN7XQ57YKGHAL6SDA772A2WVDZ6KHXPG6DRMS7VJAJ5TWGDX33LD7EPYVJ6PQ5DEFAU3FG5DJMXNXK5OZW3NMYXS2FB7TNHKNOKSZV2KA52V2BMSGLQCXSKU6GQT264OKAKJACWVXLHTDIHIOOJIRLRHVFZ6YT5II7DMDBZXAEQFL2QIB2KKWVODTPI7YIO76OAKYHKCMTDG4TKTREOJSYOMZYA6YBOL4262ANM4FGEBLSEFXSU4725ME2KJ25TRC3R23C3GGGPXJ4B5Y3ZC4X4J2WOAGVXCRC3UKVV2GATJNZ6SQ7BDPMFOVHF5RPAGP2D2YND2JRIB7ASU2RUK6VCE2J6OVVQLDSP3NAIBYJC7EYHS75N3D3NKEC7Y365EQL5E5NWOFBVKYQXVRHHWDJZAFGFD25GMF23GWBAHGTT5SO5ZVR6YVUNC22F63JAY45MAT5PHCDIIOLI5ZFIDTRG7XNPQXP6EEHFG5IGSZMSKHR37AN3UG62BTYP4RFNAZWA6PPITTC675G7XWVADWIL37YH4H62H2Q"

	scanTime := time.Now().Unix()
	listings := crawler.CrawlSearchUrl(testSearchQueryUrl)

	err = db.WriteScanToDb(dbPath, scanTime, listings)
	if err != nil {
		log.Fatal(err)
	}

	urls, err := db.GetFirstSeenListingURLs(dbPath, scanTime)
	if err != nil {
		log.Fatal(err)
	}

	if len(urls) > 0 {
		log.Println("New listings:")
		for _, url := range urls {
			log.Println(url)
		}
	} else {
		log.Println("No new listings")
	}

	// enc := json.NewEncoder(os.Stdout)
	// enc.SetIndent("", "  ")
	// enc.Encode(listings)
	// jsonEncodedListings, err := json.Marshal(listings)
	// if err != nil {
	// 	fmt.Println("Error: ", err.Error())
	// 	return
	// }
	// fmt.Printf("%v", string(jsonEncodedListings))
}
